// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPKg2TgAQ75tLEIRKKipWCfbErJec9Mkk',
    appId: '1:2890757655:web:b05f1cc8cdcaf5091bce52',
    messagingSenderId: '2890757655',
    projectId: 'prodigit-87d90',
    authDomain: 'prodigit-87d90.firebaseapp.com',
    storageBucket: 'prodigit-87d90.firebasestorage.app',
    measurementId: 'G-8KBB3TYWQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfIGDHOJ_nmVPjRlMPrJ_gi6Lec-eoNhA',
    appId: '1:2890757655:android:567e5bd7260d81e81bce52',
    messagingSenderId: '2890757655',
    projectId: 'prodigit-87d90',
    storageBucket: 'prodigit-87d90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1lXh7MFW7nPl9QzQ_z8UhKgLMRpfYpSQ',
    appId: '1:2890757655:ios:9c6d635c8d6660f81bce52',
    messagingSenderId: '2890757655',
    projectId: 'prodigit-87d90',
    storageBucket: 'prodigit-87d90.firebasestorage.app',
    iosBundleId: 'com.eranga.prodigit',
  );
}
